//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 08:13:14 PM CET 
//


package rs.ac.uns.ftn.xml_i_veb_servisi.model.potvrda_o_vakcinaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.potvrda_o_vakcinaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.potvrda_o_vakcinaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji }
     * 
     */
    public PotvrdaOVakcinaciji createPotvrdaOVakcinaciji() {
        return new PotvrdaOVakcinaciji();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.Vakcinacija }
     * 
     */
    public PotvrdaOVakcinaciji.Vakcinacija createPotvrdaOVakcinacijiVakcinacija() {
        return new PotvrdaOVakcinaciji.Vakcinacija();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.Vakcinacija.Doze }
     * 
     */
    public PotvrdaOVakcinaciji.Vakcinacija.Doze createPotvrdaOVakcinacijiVakcinacijaDoze() {
        return new PotvrdaOVakcinaciji.Vakcinacija.Doze();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.LicniPodaci }
     * 
     */
    public PotvrdaOVakcinaciji.LicniPodaci createPotvrdaOVakcinacijiLicniPodaci() {
        return new PotvrdaOVakcinaciji.LicniPodaci();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.DatumIzdavanja }
     * 
     */
    public PotvrdaOVakcinaciji.DatumIzdavanja createPotvrdaOVakcinacijiDatumIzdavanja() {
        return new PotvrdaOVakcinaciji.DatumIzdavanja();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.Vakcinacija.Doze.Doza }
     * 
     */
    public PotvrdaOVakcinaciji.Vakcinacija.Doze.Doza createPotvrdaOVakcinacijiVakcinacijaDozeDoza() {
        return new PotvrdaOVakcinaciji.Vakcinacija.Doze.Doza();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.LicniPodaci.Ime }
     * 
     */
    public PotvrdaOVakcinaciji.LicniPodaci.Ime createPotvrdaOVakcinacijiLicniPodaciIme() {
        return new PotvrdaOVakcinaciji.LicniPodaci.Ime();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.LicniPodaci.Prezime }
     * 
     */
    public PotvrdaOVakcinaciji.LicniPodaci.Prezime createPotvrdaOVakcinacijiLicniPodaciPrezime() {
        return new PotvrdaOVakcinaciji.LicniPodaci.Prezime();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.LicniPodaci.Jmbg }
     * 
     */
    public PotvrdaOVakcinaciji.LicniPodaci.Jmbg createPotvrdaOVakcinacijiLicniPodaciJmbg() {
        return new PotvrdaOVakcinaciji.LicniPodaci.Jmbg();
    }

}
