//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//


package rs.ac.uns.ftn.xml_i_veb_servisi.model.izvestaj_o_imunizaciji;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji}Period_izvestaja"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji}Podaci_o_zahtevima"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji}Lista_vakcina"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/xml_i_veb_servisi/izvestaj_o_imunizaciji}Raspodela_po_proizvodjacima"/&gt;
 *         &lt;element name="Datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "periodIzvestaja",
    "podaciOZahtevima",
    "listaVakcina",
    "raspodelaPoProizvodjacima",
    "datumIzdavanja"
})
@XmlRootElement(name = "Izvestaj_o_imunizaciji")
public class IzvestajOImunizaciji {

    @XmlElement(name = "Period_izvestaja", required = true)
    protected PeriodIzvestaja periodIzvestaja;
    @XmlElement(name = "Podaci_o_zahtevima", required = true)
    protected PodaciOZahtevima podaciOZahtevima;
    @XmlElement(name = "Lista_vakcina", required = true)
    protected ListaVakcina listaVakcina;
    @XmlElement(name = "Raspodela_po_proizvodjacima", required = true)
    protected RaspodelaPoProizvodjacima raspodelaPoProizvodjacima;
    @XmlElement(name = "Datum_izdavanja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanja;

    /**
     * Gets the value of the periodIzvestaja property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodIzvestaja }
     *     
     */
    public PeriodIzvestaja getPeriodIzvestaja() {
        return periodIzvestaja;
    }

    /**
     * Sets the value of the periodIzvestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodIzvestaja }
     *     
     */
    public void setPeriodIzvestaja(PeriodIzvestaja value) {
        this.periodIzvestaja = value;
    }

    /**
     * Gets the value of the podaciOZahtevima property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOZahtevima }
     *     
     */
    public PodaciOZahtevima getPodaciOZahtevima() {
        return podaciOZahtevima;
    }

    /**
     * Sets the value of the podaciOZahtevima property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOZahtevima }
     *     
     */
    public void setPodaciOZahtevima(PodaciOZahtevima value) {
        this.podaciOZahtevima = value;
    }

    /**
     * Gets the value of the listaVakcina property.
     * 
     * @return
     *     possible object is
     *     {@link ListaVakcina }
     *     
     */
    public ListaVakcina getListaVakcina() {
        return listaVakcina;
    }

    /**
     * Sets the value of the listaVakcina property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaVakcina }
     *     
     */
    public void setListaVakcina(ListaVakcina value) {
        this.listaVakcina = value;
    }

    /**
     * Gets the value of the raspodelaPoProizvodjacima property.
     * 
     * @return
     *     possible object is
     *     {@link RaspodelaPoProizvodjacima }
     *     
     */
    public RaspodelaPoProizvodjacima getRaspodelaPoProizvodjacima() {
        return raspodelaPoProizvodjacima;
    }

    /**
     * Sets the value of the raspodelaPoProizvodjacima property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaspodelaPoProizvodjacima }
     *     
     */
    public void setRaspodelaPoProizvodjacima(RaspodelaPoProizvodjacima value) {
        this.raspodelaPoProizvodjacima = value;
    }

    /**
     * Gets the value of the datumIzdavanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanja() {
        return datumIzdavanja;
    }

    /**
     * Sets the value of the datumIzdavanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanja(XMLGregorianCalendar value) {
        this.datumIzdavanja = value;
    }

}
