//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//


package rs.ac.uns.ftn.xml_i_veb_servisi.model.izvestaj_o_imunizaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.izvestaj_o_imunizaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.izvestaj_o_imunizaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PodaciOZahtevima }
     * 
     */
    public PodaciOZahtevima createPodaciOZahtevima() {
        return new PodaciOZahtevima();
    }

    /**
     * Create an instance of {@link IzvestajOImunizaciji }
     * 
     */
    public IzvestajOImunizaciji createIzvestajOImunizaciji() {
        return new IzvestajOImunizaciji();
    }

    /**
     * Create an instance of {@link PeriodIzvestaja }
     * 
     */
    public PeriodIzvestaja createPeriodIzvestaja() {
        return new PeriodIzvestaja();
    }

    /**
     * Create an instance of {@link PodaciOZahtevima.BrojZahteva }
     * 
     */
    public PodaciOZahtevima.BrojZahteva createPodaciOZahtevimaBrojZahteva() {
        return new PodaciOZahtevima.BrojZahteva();
    }

    /**
     * Create an instance of {@link ListaVakcina }
     * 
     */
    public ListaVakcina createListaVakcina() {
        return new ListaVakcina();
    }

    /**
     * Create an instance of {@link Vakcina }
     * 
     */
    public Vakcina createVakcina() {
        return new Vakcina();
    }

    /**
     * Create an instance of {@link RaspodelaPoProizvodjacima }
     * 
     */
    public RaspodelaPoProizvodjacima createRaspodelaPoProizvodjacima() {
        return new RaspodelaPoProizvodjacima();
    }

    /**
     * Create an instance of {@link Proizvodjac }
     * 
     */
    public Proizvodjac createProizvodjac() {
        return new Proizvodjac();
    }

}
