//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.08 at 12:01:32 PM CET 
//


package com.example.demo.model.interesovanje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.java.xml_i_veb_servisi.interesovanje package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.java.xml_i_veb_servisi.interesovanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Interesovanje }
     * 
     */
    public Interesovanje createInteresovanje() {
        return new Interesovanje();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije }
     * 
     */
    public Interesovanje.LicneInformacije createInteresovanjeLicneInformacije() {
        return new Interesovanje.LicneInformacije();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.Kontakt }
     * 
     */
    public Interesovanje.LicneInformacije.Kontakt createInteresovanjeLicneInformacijeKontakt() {
        return new Interesovanje.LicneInformacije.Kontakt();
    }

    /**
     * Create an instance of {@link Interesovanje.LokacijaPrimanjaVakcine }
     * 
     */
    public Interesovanje.LokacijaPrimanjaVakcine createInteresovanjeLokacijaPrimanjaVakcine() {
        return new Interesovanje.LokacijaPrimanjaVakcine();
    }

    /**
     * Create an instance of {@link Interesovanje.Proizvodjaci }
     * 
     */
    public Interesovanje.Proizvodjaci createInteresovanjeProizvodjaci() {
        return new Interesovanje.Proizvodjaci();
    }

    /**
     * Create an instance of {@link Interesovanje.DatumPodnosenjaInteresovanja }
     * 
     */
    public Interesovanje.DatumPodnosenjaInteresovanja createInteresovanjeDatumPodnosenjaInteresovanja() {
        return new Interesovanje.DatumPodnosenjaInteresovanja();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.Jmbg }
     * 
     */
    public Interesovanje.LicneInformacije.Jmbg createInteresovanjeLicneInformacijeJmbg() {
        return new Interesovanje.LicneInformacije.Jmbg();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.Ime }
     * 
     */
    public Interesovanje.LicneInformacije.Ime createInteresovanjeLicneInformacijeIme() {
        return new Interesovanje.LicneInformacije.Ime();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.Prezime }
     * 
     */
    public Interesovanje.LicneInformacije.Prezime createInteresovanjeLicneInformacijePrezime() {
        return new Interesovanje.LicneInformacije.Prezime();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.DavalacKrvi }
     * 
     */
    public Interesovanje.LicneInformacije.DavalacKrvi createInteresovanjeLicneInformacijeDavalacKrvi() {
        return new Interesovanje.LicneInformacije.DavalacKrvi();
    }

    /**
     * Create an instance of {@link Interesovanje.LicneInformacije.Kontakt.Email }
     * 
     */
    public Interesovanje.LicneInformacije.Kontakt.Email createInteresovanjeLicneInformacijeKontaktEmail() {
        return new Interesovanje.LicneInformacije.Kontakt.Email();
    }

}
