//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//


package main.java.xml_i_veb_servisi.model.izvestaj_o_imunizaciji;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Redni_broj_doze" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element name="Broj_datih_doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "redniBrojDoze",
    "brojDatihDoza"
})
@XmlRootElement(name = "Vakcina")
public class Vakcina {

    @XmlElement(name = "Redni_broj_doze", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger redniBrojDoze;
    @XmlElement(name = "Broj_datih_doza", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojDatihDoza;

    /**
     * Gets the value of the redniBrojDoze property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedniBrojDoze() {
        return redniBrojDoze;
    }

    /**
     * Sets the value of the redniBrojDoze property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedniBrojDoze(BigInteger value) {
        this.redniBrojDoze = value;
    }

    /**
     * Gets the value of the brojDatihDoza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDatihDoza() {
        return brojDatihDoza;
    }

    /**
     * Sets the value of the brojDatihDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDatihDoza(BigInteger value) {
        this.brojDatihDoza = value;
    }

}
