//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.08 at 12:01:32 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/interesovanje",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix = "pred", namespaceURI = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/interesovanje/predicate/")
        })
package com.example.sluzbenik_back.model.interesovanje;

import javax.xml.bind.annotation.XmlNs;