PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>
SELECT ?obrazac_saglasnosti_za_imunizaciju FROM <%s>
WHERE{
    ?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/datum_termina> ?date .
    BIND(xs:string(%s) as ?date2) .
    BIND(xs:string(?date) as ?date1) .
    FILTER ( ?date1 = ?date2)
}