PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?obrazac_saglasnosti_za_imunizaciju FROM <%s>
WHERE {
 	?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/ime> ?ime .
    ?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/prezime> ?prezime .
    ?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/jmbg> ?jmbg .
    ?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/datum_termina> ?datum .
 	?obrazac_saglasnosti_za_imunizaciju <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/obrazac_saglasnosti_za_imunizaciju/predicate/email> ?email .
    BIND(xs:string(%s) as ?ime1) .
    BIND(xs:string(%s) as ?prezime1) .
    BIND(xs:string(%s) as ?jmbg1) .
    BIND(xs:string(%s) as ?datum1) .
    BIND(xs:string(%s) as ?email1) .
    FILTER ( (?ime = ?ime1 || !(STRLEN(?ime1)>0) ) || ( ?prezime = ?prezime1 || !(STRLEN(?prezime1)>0) ) || ( ?jmbg = ?jmbg1 || !(STRLEN(?jmbg1)>0) ) || (?datum = ?datum1 || !(STRLEN(?datum1)>0) ) || (?email = ?email1 || !(STRLEN(?email1)>0)))
}
