//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:22:13 PM CET 
//


package com.example.sluzbenik_back.model.digitalni_zeleni_sertifikat;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_o_sertifikatu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Broj_sertifikata"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;positiveInteger"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_sertifikata" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Datum_i_vreme_izdavanja"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_izdavaja" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podaci_o_osobi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Ime"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Prezime"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Pol"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Muski"/&gt;
 *                         &lt;enumeration value="Zenski"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Jmbg"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TJmbg"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:jmbg" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Broj_pasosa"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TBroj_pasosa"&gt;
 *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_pasosa" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Podaci_o_vakcinaciji"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="Vakcinacija"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Tip"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="Pfizer-BioNTech"/&gt;
 *                                   &lt;enumeration value="Sputnik V"/&gt;
 *                                   &lt;enumeration value="Sinopharm"/&gt;
 *                                   &lt;enumeration value="AstraZeneca"/&gt;
 *                                   &lt;enumeration value="Moderna"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Proizvodjac"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Serija" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *                             &lt;element name="Datum"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Zdravstvena_ustanova"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="br_doze"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                                 &lt;minInclusive value="1"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Testovi"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Naziv_testa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Datum_i_vreme_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Datum_i_vreme_izdavanja_rezultata" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="qr_kod"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;minLength value="2"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Id_sertifikata"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"&gt;
 *             &lt;minExclusive value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOSertifikatu",
    "podaciOOsobi",
    "podaciOVakcinaciji",
    "testovi",
    "datum"
})
@XmlRootElement(name = "Digitalni_zeleni_sertifikat")
public class DigitalniZeleniSertifikat {

    @XmlElement(name = "Podaci_o_sertifikatu", required = true)
    protected PodaciOSertifikatu podaciOSertifikatu;
    @XmlElement(name = "Podaci_o_osobi", required = true)
    protected PodaciOOsobi podaciOOsobi;
    @XmlElement(name = "Podaci_o_vakcinaciji", required = true)
    protected PodaciOVakcinaciji podaciOVakcinaciji;
    @XmlElement(name = "Testovi", required = true)
    protected Testovi testovi;
    @XmlElement(name = "Datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "qr_kod")
    protected String qrKod;
    @XmlAttribute(name = "Id_sertifikata")
    protected BigInteger idSertifikata;
    @XmlAttribute(name = "about")
    protected String about;

    /**
     * Gets the value of the podaciOSertifikatu property.
     *
     * @return
     *     possible object is
     *     {@link PodaciOSertifikatu }
     *
     */
    public PodaciOSertifikatu getPodaciOSertifikatu() {
        return podaciOSertifikatu;
    }

    /**
     * Sets the value of the podaciOSertifikatu property.
     *
     * @param value
     *     allowed object is
     *     {@link PodaciOSertifikatu }
     *
     */
    public void setPodaciOSertifikatu(PodaciOSertifikatu value) {
        this.podaciOSertifikatu = value;
    }

    /**
     * Gets the value of the podaciOOsobi property.
     *
     * @return
     *     possible object is
     *     {@link PodaciOOsobi }
     *
     */
    public PodaciOOsobi getPodaciOOsobi() {
        return podaciOOsobi;
    }

    /**
     * Sets the value of the podaciOOsobi property.
     *
     * @param value
     *     allowed object is
     *     {@link PodaciOOsobi }
     *
     */
    public void setPodaciOOsobi(PodaciOOsobi value) {
        this.podaciOOsobi = value;
    }

    /**
     * Gets the value of the podaciOVakcinaciji property.
     *
     * @return
     *     possible object is
     *     {@link PodaciOVakcinaciji }
     *
     */
    public PodaciOVakcinaciji getPodaciOVakcinaciji() {
        return podaciOVakcinaciji;
    }

    /**
     * Sets the value of the podaciOVakcinaciji property.
     *
     * @param value
     *     allowed object is
     *     {@link PodaciOVakcinaciji }
     *
     */
    public void setPodaciOVakcinaciji(PodaciOVakcinaciji value) {
        this.podaciOVakcinaciji = value;
    }

    /**
     * Gets the value of the testovi property.
     *
     * @return
     *     possible object is
     *     {@link Testovi }
     *
     */
    public Testovi getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     *
     * @param value
     *     allowed object is
     *     {@link Testovi }
     *
     */
    public void setTestovi(Testovi value) {
        this.testovi = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the qrKod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQrKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQrKod(String value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the idSertifikata property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getIdSertifikata() {
        return idSertifikata;
    }

    /**
     * Sets the value of the idSertifikata property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setIdSertifikata(BigInteger value) {
        this.idSertifikata = value;
    }

    /**
     * Gets the value of the about property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbout(String value) {
        this.about = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Ime"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Prezime"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Pol"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Muski"/&gt;
     *               &lt;enumeration value="Zenski"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Datum_rodjenja" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Jmbg"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TJmbg"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:jmbg" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Broj_pasosa"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TBroj_pasosa"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_pasosa" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "pol",
        "datumRodjenja",
        "jmbg",
        "brojPasosa"
    })
    public static class PodaciOOsobi {

        @XmlElement(name = "Ime", required = true)
        protected Ime ime;
        @XmlElement(name = "Prezime", required = true)
        protected Prezime prezime;
        @XmlElement(name = "Pol", required = true)
        protected String pol;
        @XmlElement(name = "Datum_rodjenja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumRodjenja;
        @XmlElement(name = "Jmbg", required = true)
        protected Jmbg jmbg;
        @XmlElement(name = "Broj_pasosa", required = true)
        protected BrojPasosa brojPasosa;

        /**
         * Gets the value of the ime property.
         *
         * @return
         *     possible object is
         *     {@link Ime }
         *
         */
        public Ime getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         *
         * @param value
         *     allowed object is
         *     {@link Ime }
         *
         */
        public void setIme(Ime value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         *
         * @return
         *     possible object is
         *     {@link Prezime }
         *
         */
        public Prezime getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         *
         * @param value
         *     allowed object is
         *     {@link Prezime }
         *
         */
        public void setPrezime(Prezime value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the pol property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPol() {
            return pol;
        }

        /**
         * Sets the value of the pol property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPol(String value) {
            this.pol = value;
        }

        /**
         * Gets the value of the datumRodjenja property.
         *
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getDatumRodjenja() {
            return datumRodjenja;
        }

        /**
         * Sets the value of the datumRodjenja property.
         *
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *
         */
        public void setDatumRodjenja(XMLGregorianCalendar value) {
            this.datumRodjenja = value;
        }

        /**
         * Gets the value of the jmbg property.
         *
         * @return
         *     possible object is
         *     {@link Jmbg }
         *
         */
        public Jmbg getJmbg() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         *
         * @param value
         *     allowed object is
         *     {@link Jmbg }
         *
         */
        public void setJmbg(Jmbg value) {
            this.jmbg = value;
        }

        /**
         * Gets the value of the brojPasosa property.
         *
         * @return
         *     possible object is
         *     {@link BrojPasosa }
         *
         */
        public BrojPasosa getBrojPasosa() {
            return brojPasosa;
        }

        /**
         * Sets the value of the brojPasosa property.
         *
         * @param value
         *     allowed object is
         *     {@link BrojPasosa }
         *
         */
        public void setBrojPasosa(BrojPasosa value) {
            this.brojPasosa = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TBroj_pasosa"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_pasosa" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BrojPasosa {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:broj_pasosa";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Ime {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:ime";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat&gt;TJmbg"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:jmbg" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Jmbg {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:jmbg";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Prezime {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:prezime";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Broj_sertifikata"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;positiveInteger"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_sertifikata" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Datum_i_vreme_izdavanja"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
     *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_izdavaja" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojSertifikata",
        "datumIVremeIzdavanja"
    })
    public static class PodaciOSertifikatu {

        @XmlElement(name = "Broj_sertifikata", required = true)
        protected BrojSertifikata brojSertifikata;
        @XmlElement(name = "Datum_i_vreme_izdavanja", required = true)
        protected DatumIVremeIzdavanja datumIVremeIzdavanja;

        /**
         * Gets the value of the brojSertifikata property.
         *
         * @return
         *     possible object is
         *     {@link BrojSertifikata }
         *
         */
        public BrojSertifikata getBrojSertifikata() {
            return brojSertifikata;
        }

        /**
         * Sets the value of the brojSertifikata property.
         *
         * @param value
         *     allowed object is
         *     {@link BrojSertifikata }
         *
         */
        public void setBrojSertifikata(BrojSertifikata value) {
            this.brojSertifikata = value;
        }

        /**
         * Gets the value of the datumIVremeIzdavanja property.
         *
         * @return
         *     possible object is
         *     {@link DatumIVremeIzdavanja }
         *
         */
        public DatumIVremeIzdavanja getDatumIVremeIzdavanja() {
            return datumIVremeIzdavanja;
        }

        /**
         * Sets the value of the datumIVremeIzdavanja property.
         *
         * @param value
         *     allowed object is
         *     {@link DatumIVremeIzdavanja }
         *
         */
        public void setDatumIVremeIzdavanja(DatumIVremeIzdavanja value) {
            this.datumIVremeIzdavanja = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;positiveInteger"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:broj_sertifikata" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BrojSertifikata {

            @XmlValue
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setValue(BigInteger value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:broj_sertifikata";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;dateTime"&gt;
         *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:datum_izdavaja" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DatumIVremeIzdavanja {

            @XmlValue
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar value;
            @XmlAttribute(name = "property")
            protected String property;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setValue(XMLGregorianCalendar value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:datum_izdavaja";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setProperty(String value) {
                this.property = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="Vakcinacija"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Tip"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="Pfizer-BioNTech"/&gt;
     *                         &lt;enumeration value="Sputnik V"/&gt;
     *                         &lt;enumeration value="Sinopharm"/&gt;
     *                         &lt;enumeration value="AstraZeneca"/&gt;
     *                         &lt;enumeration value="Moderna"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Proizvodjac"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Serija" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
     *                   &lt;element name="Datum"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Zdravstvena_ustanova"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="br_doze"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *                       &lt;minInclusive value="1"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vakcinacija"
    })
    public static class PodaciOVakcinaciji {

        @XmlElement(name = "Vakcinacija", required = true)
        protected List<Vakcinacija> vakcinacija;

        /**
         * Gets the value of the vakcinacija property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcinacija property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcinacija().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vakcinacija }
         *
         *
         */
        public List<Vakcinacija> getVakcinacija() {
            if (vakcinacija == null) {
                vakcinacija = new ArrayList<Vakcinacija>();
            }
            return this.vakcinacija;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Tip"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="Pfizer-BioNTech"/&gt;
         *               &lt;enumeration value="Sputnik V"/&gt;
         *               &lt;enumeration value="Sinopharm"/&gt;
         *               &lt;enumeration value="AstraZeneca"/&gt;
         *               &lt;enumeration value="Moderna"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Proizvodjac"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Serija" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
         *         &lt;element name="Datum"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Zdravstvena_ustanova"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="br_doze"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
         *             &lt;minInclusive value="1"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tip",
            "proizvodjac",
            "serija",
            "datum",
            "zdravstvenaUstanova"
        })
        public static class Vakcinacija {

            @XmlElement(name = "Tip", required = true)
            protected String tip;
            @XmlElement(name = "Proizvodjac", required = true)
            protected Proizvodjac proizvodjac;
            @XmlElement(name = "Serija", required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger serija;
            @XmlElement(name = "Datum", required = true)
            protected Datum datum;
            @XmlElement(name = "Zdravstvena_ustanova", required = true)
            protected ZdravstvenaUstanova zdravstvenaUstanova;
            @XmlAttribute(name = "br_doze")
            protected Integer brDoze;

            /**
             * Gets the value of the tip property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTip() {
                return tip;
            }

            /**
             * Sets the value of the tip property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTip(String value) {
                this.tip = value;
            }

            /**
             * Gets the value of the proizvodjac property.
             *
             * @return
             *     possible object is
             *     {@link Proizvodjac }
             *
             */
            public Proizvodjac getProizvodjac() {
                return proizvodjac;
            }

            /**
             * Sets the value of the proizvodjac property.
             *
             * @param value
             *     allowed object is
             *     {@link Proizvodjac }
             *
             */
            public void setProizvodjac(Proizvodjac value) {
                this.proizvodjac = value;
            }

            /**
             * Gets the value of the serija property.
             *
             * @return
             *     possible object is
             *     {@link BigInteger }
             *
             */
            public BigInteger getSerija() {
                return serija;
            }

            /**
             * Sets the value of the serija property.
             *
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *
             */
            public void setSerija(BigInteger value) {
                this.serija = value;
            }

            /**
             * Gets the value of the datum property.
             *
             * @return
             *     possible object is
             *     {@link Datum }
             *
             */
            public Datum getDatum() {
                return datum;
            }

            /**
             * Sets the value of the datum property.
             *
             * @param value
             *     allowed object is
             *     {@link Datum }
             *
             */
            public void setDatum(Datum value) {
                this.datum = value;
            }

            /**
             * Gets the value of the zdravstvenaUstanova property.
             *
             * @return
             *     possible object is
             *     {@link ZdravstvenaUstanova }
             *
             */
            public ZdravstvenaUstanova getZdravstvenaUstanova() {
                return zdravstvenaUstanova;
            }

            /**
             * Sets the value of the zdravstvenaUstanova property.
             *
             * @param value
             *     allowed object is
             *     {@link ZdravstvenaUstanova }
             *
             */
            public void setZdravstvenaUstanova(ZdravstvenaUstanova value) {
                this.zdravstvenaUstanova = value;
            }

            /**
             * Gets the value of the brDoze property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBrDoze() {
                return brDoze;
            }

            /**
             * Sets the value of the brDoze property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBrDoze(Integer value) {
                this.brDoze = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Datum {

                @XmlValue
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setValue(XMLGregorianCalendar value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Proizvodjac {

                @XmlValue
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ZdravstvenaUstanova {

                @XmlValue
                protected String value;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Naziv_testa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Vrsta_uzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Datum_i_vreme_uzorkovanja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Datum_i_vreme_izdavanja_rezultata" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivTesta",
        "vrstaUzorka",
        "datumIVremeUzorkovanja",
        "datumIVremeIzdavanjaRezultata"
    })
    public static class Testovi {

        @XmlElement(name = "Naziv_testa", required = true)
        protected String nazivTesta;
        @XmlElement(name = "Vrsta_uzorka", required = true)
        protected String vrstaUzorka;
        @XmlElement(name = "Datum_i_vreme_uzorkovanja", required = true)
        protected String datumIVremeUzorkovanja;
        @XmlElement(name = "Datum_i_vreme_izdavanja_rezultata", required = true)
        protected String datumIVremeIzdavanjaRezultata;

        /**
         * Gets the value of the nazivTesta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivTesta() {
            return nazivTesta;
        }

        /**
         * Sets the value of the nazivTesta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivTesta(String value) {
            this.nazivTesta = value;
        }

        /**
         * Gets the value of the vrstaUzorka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVrstaUzorka() {
            return vrstaUzorka;
        }

        /**
         * Sets the value of the vrstaUzorka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVrstaUzorka(String value) {
            this.vrstaUzorka = value;
        }

        /**
         * Gets the value of the datumIVremeUzorkovanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumIVremeUzorkovanja() {
            return datumIVremeUzorkovanja;
        }

        /**
         * Sets the value of the datumIVremeUzorkovanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumIVremeUzorkovanja(String value) {
            this.datumIVremeUzorkovanja = value;
        }

        /**
         * Gets the value of the datumIVremeIzdavanjaRezultata property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumIVremeIzdavanjaRezultata() {
            return datumIVremeIzdavanjaRezultata;
        }

        /**
         * Sets the value of the datumIVremeIzdavanjaRezultata property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumIVremeIzdavanjaRezultata(String value) {
            this.datumIVremeIzdavanjaRezultata = value;
        }

    }

}
