//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.09 at 12:17:23 PM CET 
//


package com.example.demo.model.dostupne_vakcine;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.dostupne_vakcine package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.dostupne_vakcine
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zalihe }
     * 
     */
    public Zalihe createZalihe() {
        return new Zalihe();
    }

    /**
     * Create an instance of {@link Zalihe.Vakcina }
     * 
     */
    public Zalihe.Vakcina createZaliheVakcina() {
        return new Zalihe.Vakcina();
    }

}
