//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:22:13 PM CET 
//


package rs.ac.uns.ftn.xml_i_veb_servisi.model.digitalni_zeleni_sertifikat;

import rs.ac.uns.ftn.xml_i_veb_servisi.model.digitalni_zeleni_sertifikat.DigitalniZeleniSertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.digitalni_zeleni_sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.digitalni_zeleni_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat }
     * 
     */
    public DigitalniZeleniSertifikat createDigitalniZeleniSertifikat() {
        return new DigitalniZeleniSertifikat();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOVakcinaciji }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOVakcinaciji createDigitalniZeleniSertifikatPodaciOVakcinaciji() {
        return new DigitalniZeleniSertifikat.PodaciOVakcinaciji();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija createDigitalniZeleniSertifikatPodaciOVakcinacijiVakcinacija() {
        return new DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOOsobi }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOOsobi createDigitalniZeleniSertifikatPodaciOOsobi() {
        return new DigitalniZeleniSertifikat.PodaciOOsobi();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOSertifikatu }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOSertifikatu createDigitalniZeleniSertifikatPodaciOSertifikatu() {
        return new DigitalniZeleniSertifikat.PodaciOSertifikatu();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.Testovi }
     * 
     */
    public DigitalniZeleniSertifikat.Testovi createDigitalniZeleniSertifikatTestovi() {
        return new DigitalniZeleniSertifikat.Testovi();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Proizvodjac }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Proizvodjac createDigitalniZeleniSertifikatPodaciOVakcinacijiVakcinacijaProizvodjac() {
        return new DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Proizvodjac();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Datum }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Datum createDigitalniZeleniSertifikatPodaciOVakcinacijiVakcinacijaDatum() {
        return new DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.Datum();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.ZdravstvenaUstanova }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.ZdravstvenaUstanova createDigitalniZeleniSertifikatPodaciOVakcinacijiVakcinacijaZdravstvenaUstanova() {
        return new DigitalniZeleniSertifikat.PodaciOVakcinaciji.Vakcinacija.ZdravstvenaUstanova();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOOsobi.Ime }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOOsobi.Ime createDigitalniZeleniSertifikatPodaciOOsobiIme() {
        return new DigitalniZeleniSertifikat.PodaciOOsobi.Ime();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOOsobi.Prezime }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOOsobi.Prezime createDigitalniZeleniSertifikatPodaciOOsobiPrezime() {
        return new DigitalniZeleniSertifikat.PodaciOOsobi.Prezime();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOOsobi.Jmbg }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOOsobi.Jmbg createDigitalniZeleniSertifikatPodaciOOsobiJmbg() {
        return new DigitalniZeleniSertifikat.PodaciOOsobi.Jmbg();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOOsobi.BrojPasosa }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOOsobi.BrojPasosa createDigitalniZeleniSertifikatPodaciOOsobiBrojPasosa() {
        return new DigitalniZeleniSertifikat.PodaciOOsobi.BrojPasosa();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOSertifikatu.BrojSertifikata }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOSertifikatu.BrojSertifikata createDigitalniZeleniSertifikatPodaciOSertifikatuBrojSertifikata() {
        return new DigitalniZeleniSertifikat.PodaciOSertifikatu.BrojSertifikata();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOSertifikatu.DatumIVremeIzdavanja }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOSertifikatu.DatumIVremeIzdavanja createDigitalniZeleniSertifikatPodaciOSertifikatuDatumIVremeIzdavanja() {
        return new DigitalniZeleniSertifikat.PodaciOSertifikatu.DatumIVremeIzdavanja();
    }

}
