//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.06 at 01:22:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/digitalni_zeleni_sertifikat", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.ac.uns.ftn.xml_i_veb_servisi.model.digitalni_zeleni_sertifikat;
