//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//


package com.example.sluzbenik_back.model.izvestaj_o_imunizaciji;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ime_proizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Broj_doza" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imeProizvodjaca",
    "brojDoza"
})
@XmlRootElement(name = "Proizvodjac")
public class Proizvodjac {

    @XmlElement(name = "Ime_proizvodjaca", required = true)
    protected String imeProizvodjaca;
    @XmlElement(name = "Broj_doza", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brojDoza;

    /**
     * Gets the value of the imeProizvodjaca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeProizvodjaca() {
        return imeProizvodjaca;
    }

    /**
     * Sets the value of the imeProizvodjaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeProizvodjaca(String value) {
        this.imeProizvodjaca = value;
    }

    /**
     * Gets the value of the brojDoza property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojDoza() {
        return brojDoza;
    }

    /**
     * Sets the value of the brojDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojDoza(BigInteger value) {
        this.brojDoza = value;
    }

}
