//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//


package rs.ac.uns.ftn.xml_i_veb_servisi.model.obrazac_saglasnosti_za_imunizaciju;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.obrazac_saglasnosti_za_imunizaciju package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SaglasnostEvidencijaOVakcinacijiVakcinePrivremeneKontraindikacijeDatumUtvrdjivanja_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju", "Datum_utvrdjivanja");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.obrazac_saglasnosti_za_imunizaciju
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Saglasnost }
     * 
     */
    public Saglasnost createSaglasnost() {
        return new Saglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost.EvidencijaOVakcinaciji }
     * 
     */
    public Saglasnost.EvidencijaOVakcinaciji createSaglasnostEvidencijaOVakcinaciji() {
        return new Saglasnost.EvidencijaOVakcinaciji();
    }

    /**
     * Create an instance of {@link Saglasnost.EvidencijaOVakcinaciji.Vakcine }
     * 
     */
    public Saglasnost.EvidencijaOVakcinaciji.Vakcine createSaglasnostEvidencijaOVakcinacijiVakcine() {
        return new Saglasnost.EvidencijaOVakcinaciji.Vakcine();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent }
     * 
     */
    public Saglasnost.Pacijent createSaglasnostPacijent() {
        return new Saglasnost.Pacijent();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.LicniPodaci }
     * 
     */
    public Saglasnost.Pacijent.LicniPodaci createSaglasnostPacijentLicniPodaci() {
        return new Saglasnost.Pacijent.LicniPodaci();
    }

    /**
     * Create an instance of {@link Saglasnost.EvidencijaOVakcinaciji.Lekar }
     * 
     */
    public Saglasnost.EvidencijaOVakcinaciji.Lekar createSaglasnostEvidencijaOVakcinacijiLekar() {
        return new Saglasnost.EvidencijaOVakcinaciji.Lekar();
    }

    /**
     * Create an instance of {@link Saglasnost.EvidencijaOVakcinaciji.Vakcine.Vakcina }
     * 
     */
    public Saglasnost.EvidencijaOVakcinaciji.Vakcine.Vakcina createSaglasnostEvidencijaOVakcinacijiVakcineVakcina() {
        return new Saglasnost.EvidencijaOVakcinaciji.Vakcine.Vakcina();
    }

    /**
     * Create an instance of {@link Saglasnost.EvidencijaOVakcinaciji.Vakcine.PrivremeneKontraindikacije }
     * 
     */
    public Saglasnost.EvidencijaOVakcinaciji.Vakcine.PrivremeneKontraindikacije createSaglasnostEvidencijaOVakcinacijiVakcinePrivremeneKontraindikacije() {
        return new Saglasnost.EvidencijaOVakcinaciji.Vakcine.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.DrzavljaninSrbije }
     * 
     */
    public Saglasnost.Pacijent.DrzavljaninSrbije createSaglasnostPacijentDrzavljaninSrbije() {
        return new Saglasnost.Pacijent.DrzavljaninSrbije();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.StraniDrzavljanin }
     * 
     */
    public Saglasnost.Pacijent.StraniDrzavljanin createSaglasnostPacijentStraniDrzavljanin() {
        return new Saglasnost.Pacijent.StraniDrzavljanin();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.SaglasnostPacijenta }
     * 
     */
    public Saglasnost.Pacijent.SaglasnostPacijenta createSaglasnostPacijentSaglasnostPacijenta() {
        return new Saglasnost.Pacijent.SaglasnostPacijenta();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.LicniPodaci.Adresa }
     * 
     */
    public Saglasnost.Pacijent.LicniPodaci.Adresa createSaglasnostPacijentLicniPodaciAdresa() {
        return new Saglasnost.Pacijent.LicniPodaci.Adresa();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.LicniPodaci.KontaktInformacije }
     * 
     */
    public Saglasnost.Pacijent.LicniPodaci.KontaktInformacije createSaglasnostPacijentLicniPodaciKontaktInformacije() {
        return new Saglasnost.Pacijent.LicniPodaci.KontaktInformacije();
    }

    /**
     * Create an instance of {@link Saglasnost.Pacijent.LicniPodaci.SocijalnaZastita }
     * 
     */
    public Saglasnost.Pacijent.LicniPodaci.SocijalnaZastita createSaglasnostPacijentLicniPodaciSocijalnaZastita() {
        return new Saglasnost.Pacijent.LicniPodaci.SocijalnaZastita();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/obrazac_saglasnosti_za_imunizaciju", name = "Datum_utvrdjivanja", scope = Saglasnost.EvidencijaOVakcinaciji.Vakcine.PrivremeneKontraindikacije.class)
    public JAXBElement<XMLGregorianCalendar> createSaglasnostEvidencijaOVakcinacijiVakcinePrivremeneKontraindikacijeDatumUtvrdjivanja(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SaglasnostEvidencijaOVakcinacijiVakcinePrivremeneKontraindikacijeDatumUtvrdjivanja_QNAME, XMLGregorianCalendar.class, Saglasnost.EvidencijaOVakcinaciji.Vakcine.PrivremeneKontraindikacije.class, value);
    }

}
