//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 02:16:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/zahtev_za_sertifikatom",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix = "pred", namespaceURI = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/zahtev_za_sertifikatom/predicate/")
        })
package com.example.demo.model.zahtev_za_sertifikatom;

import javax.xml.bind.annotation.XmlNs;