PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>
SELECT ?digitalni_zeleni_sertifikat FROM <%s>
WHERE {
    ?digitalni_zeleni_sertifikat <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/digitalni_zeleni_sertifikat/predicate/jmbg> ?jmbg .
    BIND(xs:string(%s) as ?searchedJmbg) .
    BIND(xs:string(?jmbg) as ?presentJmbg) .
    FILTER( ?searchedJmbg = ?presentJmbg )
}