PREFIX xs:     <http://www.w3.org/2001/XMLSchema#>
SELECT ?potvrda_o_vakcinaciji FROM <%s>
WHERE {
    ?potvrda_o_vakcinaciji <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/datum_izdavanja> ?date .
    ?potvrda_o_vakcinaciji <http://www.ftn.uns.ac.rs/xml_i_veb_servisi/rdf/potvrda_o_vakcinaciji/predicate/jmbg> ?jmbg .
    BIND(xs:string(%s) as ?searchedJmbg) .
    BIND(xs:string(?jmbg) as ?presentJmbg) .
    BIND(xs:string(%s) as ?currentDate) .
    BIND(xs:string(?date) as ?presentDate) .
    FILTER ( ?currentDate = ?presentDate && ?searchedJmbg = ?presentJmbg)
}