//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.08 at 08:08:58 PM CET 
//


package com.example.sluzbenik_back.model.korisnik;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.xml_i_veb_servisi.korisnik package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ime_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "ime");
    private final static QName _Prezime_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "prezime");
    private final static QName _Pol_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "pol");
    private final static QName _Rodjendan_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "rodjendan");
    private final static QName _Email_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "email");
    private final static QName _Lozinka_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "lozinka");
    private final static QName _Uloga_QNAME = new QName("http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", "uloga");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.xml_i_veb_servisi.korisnik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaKorisnika }
     * 
     */
    public ListaKorisnika createListaKorisnika() {
        return new ListaKorisnika();
    }

    /**
     * Create an instance of {@link Korisnik }
     * 
     */
    public Korisnik createKorisnik() {
        return new Korisnik();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "ime")
    public JAXBElement<String> createIme(String value) {
        return new JAXBElement<String>(_Ime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "prezime")
    public JAXBElement<String> createPrezime(String value) {
        return new JAXBElement<String>(_Prezime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "pol")
    public JAXBElement<String> createPol(String value) {
        return new JAXBElement<String>(_Pol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "rodjendan")
    public JAXBElement<String> createRodjendan(String value) {
        return new JAXBElement<String>(_Rodjendan_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "lozinka")
    public JAXBElement<String> createLozinka(String value) {
        return new JAXBElement<String>(_Lozinka_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/xml_i_veb_servisi/korisnik", name = "uloga")
    public JAXBElement<String> createUloga(String value) {
        return new JAXBElement<String>(_Uloga_QNAME, String.class, null, value);
    }

}
